### ISSUE TITLE
Allow for mapping of additional subdomains to a site

### ISSUE THREAD

**Issue by daveanastasi** [imarc/ops#2]
Use case: building an site having a codebase that serves multiple subdomains (like an intranet). Would like to be able to set up something like:

* marketing.my-company.imarc.io
* finance.my-company.imarc.io
* hr.my-company.imarc.io
etc...

If it simplifies things, the subdomains could be hardcoded into the .env rather than served via wildcards.

**Comment by jeffturcotte** [comment]
Feature added in 0.8.4 release
