### ISSUE TITLE
Need to install mkcert manually

### ISSUE THREAD

**Issue by ellierider** [imarc/ops#28]
Installing on a new Mac today, I saw this output:

```
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "brew install nss" and re-run "mkcert -install" 👈
```

I followed the instructions but then saw:
```
% mkcert -install
zsh: command not found: mkcert
```

I tried a new session, same results. 

Then I ran `brew install mkcert` and reran `mkcert -install` and it worked.

Should I update the instructions to include installing mkcert alongside nss?

**Comment by kyleridolfo** [comment]
FYI this does not seem to resolve cert errors in Firefox
